/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TiqqeButton {
        "color": "primary" | "secondary" | "danger" | "success";
        "label": string;
    }
}
declare global {
    interface HTMLTiqqeButtonElement extends Components.TiqqeButton, HTMLStencilElement {
    }
    var HTMLTiqqeButtonElement: {
        prototype: HTMLTiqqeButtonElement;
        new (): HTMLTiqqeButtonElement;
    };
    interface HTMLElementTagNameMap {
        "tiqqe-button": HTMLTiqqeButtonElement;
    }
}
declare namespace LocalJSX {
    interface TiqqeButton {
        "color"?: "primary" | "secondary" | "danger" | "success";
        "label"?: string;
    }
    interface IntrinsicElements {
        "tiqqe-button": TiqqeButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tiqqe-button": LocalJSX.TiqqeButton & JSXBase.HTMLAttributes<HTMLTiqqeButtonElement>;
        }
    }
}
